<?php
if (!defined("ABSPATH")) {
    exit();
}

$service_addresses_2 = [
    0 => [
        'county' => 'San Diego',
        'city' => 'Alpine',
        'zip' => '91901',
        'price' => '95.00',
        'service' => 2,
    ],
    1 => [
        'county' => 'San Diego',
        'city' => 'Alpine',
        'zip' => '91903',
        'price' => '95.00',
        'service' => 2,
    ],
    2 => [
        'county' => 'San Diego',
        'city' => 'Bonita',
        'zip' => '91902',
        'price' => '75.00',
        'service' => 2,
    ],
    3 => [
        'county' => 'San Diego',
        'city' => 'Bonita',
        'zip' => '91905',
        'price' => '125.00',
        'service' => 2,
    ],
    4 => [
        'county' => 'San Diego',
        'city' => 'Bonsall',
        'zip' => '91906',
        'price' => '125.00',
        'service' => 2,
    ],
    5 => [
        'county' => 'San Diego',
        'city' => 'Borrego Springs',
        'zip' => '91908',
        'price' => '300.00',
        'service' => 2,
    ],
    6 => [
        'county' => 'San Diego',
        'city' => 'Boulevard',
        'zip' => '91909',
        'price' => '300.00',
        'service' => 2,
    ],
    7 => [
        'county' => 'San Diego',
        'city' => 'Camp Pendleton',
        'zip' => '91910',
        'price' => '75.00',
        'service' => 2,
    ],
    8 => [
        'county' => 'San Diego',
        'city' => 'Camp Pendleton',
        'zip' => '91911',
        'price' => '75.00',
        'service' => 2,
    ],
    9 => [
        'county' => 'San Diego',
        'city' => 'Campo',
        'zip' => '91912',
        'price' => '75.00',
        'service' => 2,
    ],
    10 => [
        'county' => 'San Diego',
        'city' => 'Cardiff',
        'zip' => '91913',
        'price' => '75.00',
        'service' => 2,
    ],
    11 => [
        'county' => 'San Diego',
        'city' => 'Carlsbad',
        'zip' => '91914',
        'price' => '75.00',
        'service' => 2,
    ],
    12 => [
        'county' => 'San Diego',
        'city' => 'Carlsbad',
        'zip' => '91915',
        'price' => '75.00',
        'service' => 2,
    ],
    13 => [
        'county' => 'San Diego',
        'city' => 'Carlsbad',
        'zip' => '91916',
        'price' => '95.00',
        'service' => 2,
    ],
    14 => [
        'county' => 'San Diego',
        'city' => 'Carlsbad',
        'zip' => '91917',
        'price' => '95.00',
        'service' => 2,
    ],
    15 => [
        'county' => 'San Diego',
        'city' => 'Chula Vista',
        'zip' => '91921',
        'price' => '75.00',
        'service' => 2,
    ],
    16 => [
        'county' => 'San Diego',
        'city' => 'Chula Vista',
        'zip' => '91931',
        'price' => '95.00',
        'service' => 2,
    ],
    17 => [
        'county' => 'San Diego',
        'city' => 'Chula Vista',
        'zip' => '91932',
        'price' => '75.00',
        'service' => 2,
    ],
    18 => [
        'county' => 'San Diego',
        'city' => 'Chula Vista',
        'zip' => '91933',
        'price' => '75.00',
        'service' => 2,
    ],
    19 => [
        'county' => 'San Diego',
        'city' => 'Chula Vista',
        'zip' => '91934',
        'price' => '125.00',
        'service' => 2,
    ],
    20 => [
        'county' => 'San Diego',
        'city' => 'Chula Vista',
        'zip' => '91935',
        'price' => '95.00',
        'service' => 2,
    ],
    21 => [
        'county' => 'San Diego',
        'city' => 'Chula Vista',
        'zip' => '91941',
        'price' => '75.00',
        'service' => 2,
    ],
    22 => [
        'county' => 'San Diego',
        'city' => 'Chula Vista',
        'zip' => '91942',
        'price' => '75.00',
        'service' => 2,
    ],
    23 => [
        'county' => 'San Diego',
        'city' => 'Coronado',
        'zip' => '91943',
        'price' => '75.00',
        'service' => 2,
    ],
    24 => [
        'county' => 'San Diego',
        'city' => 'Coronado',
        'zip' => '91944',
        'price' => '75.00',
        'service' => 2,
    ],
    25 => [
        'county' => 'San Diego',
        'city' => 'Del Mar',
        'zip' => '91945',
        'price' => '75.00',
        'service' => 2,
    ],
    26 => [
        'county' => 'San Diego',
        'city' => 'Descanso',
        'zip' => '91946',
        'price' => '300.00',
        'service' => 2,
    ],
    27 => [
        'county' => 'San Diego',
        'city' => 'Dulzura',
        'zip' => '91947',
        'price' => '75.00',
        'service' => 2,
    ],
    28 => [
        'county' => 'San Diego',
        'city' => 'El Cajon',
        'zip' => '91948',
        'price' => '75.00',
        'service' => 2,
    ],
    29 => [
        'county' => 'San Diego',
        'city' => 'El Cajon',
        'zip' => '91950',
        'price' => '75.00',
        'service' => 2,
    ],
    30 => [
        'county' => 'San Diego',
        'city' => 'El Cajon',
        'zip' => '91951',
        'price' => '75.00',
        'service' => 2,
    ],
    31 => [
        'county' => 'San Diego',
        'city' => 'El Cajon',
        'zip' => '91962',
        'price' => '95.00',
        'service' => 2,
    ],
    32 => [
        'county' => 'San Diego',
        'city' => 'Encinitas',
        'zip' => '91963',
        'price' => '75.00',
        'service' => 2,
    ],
    33 => [
        'county' => 'San Diego',
        'city' => 'Encinitas',
        'zip' => '91976',
        'price' => '75.00',
        'service' => 2,
    ],
    34 => [
        'county' => 'San Diego',
        'city' => 'Escondido',
        'zip' => '91977',
        'price' => '75.00',
        'service' => 2,
    ],
    35 => [
        'county' => 'San Diego',
        'city' => 'Escondido',
        'zip' => '91978',
        'price' => '75.00',
        'service' => 2,
    ],
    36 => [
        'county' => 'San Diego',
        'city' => 'Escondido',
        'zip' => '91979',
        'price' => '75.00',
        'service' => 2,
    ],
    37 => [
        'county' => 'San Diego',
        'city' => 'Escondido',
        'zip' => '91980',
        'price' => '125.00',
        'service' => 2,
    ],
    38 => [
        'county' => 'San Diego',
        'city' => 'Escondido',
        'zip' => '92003',
        'price' => '75.00',
        'service' => 2,
    ],
    39 => [
        'county' => 'San Diego',
        'city' => 'Escondido',
        'zip' => '92004',
        'price' => '145.00',
        'service' => 2,
    ],
    40 => [
        'county' => 'San Diego',
        'city' => 'Escondido',
        'zip' => '92007',
        'price' => '75.00',
        'service' => 2,
    ],
    41 => [
        'county' => 'San Diego',
        'city' => 'Fallbrook',
        'zip' => '92008',
        'price' => '75.00',
        'service' => 2,
    ],
    42 => [
        'county' => 'San Diego',
        'city' => 'Fallbrook',
        'zip' => '92009',
        'price' => '75.00',
        'service' => 2,
    ],
    43 => [
        'county' => 'San Diego',
        'city' => 'Guatay',
        'zip' => '92013',
        'price' => '75.00',
        'service' => 2,
    ],
    44 => [
        'county' => 'San Diego',
        'city' => 'Imperial Beach',
        'zip' => '92014',
        'price' => '75.00',
        'service' => 2,
    ],
    45 => [
        'county' => 'San Diego',
        'city' => 'Imperial Beach',
        'zip' => '92018',
        'price' => '75.00',
        'service' => 2,
    ],
    46 => [
        'county' => 'San Diego',
        'city' => 'Jacumba',
        'zip' => '92019',
        'price' => '75.00',
        'service' => 2,
    ],
    47 => [
        'county' => 'San Diego',
        'city' => 'Jamul',
        'zip' => '92020',
        'price' => '75.00',
        'service' => 2,
    ],
    48 => [
        'county' => 'San Diego',
        'city' => 'Julian',
        'zip' => '92021',
        'price' => '75.00',
        'service' => 2,
    ],
    49 => [
        'county' => 'San Diego',
        'city' => 'La Jolla',
        'zip' => '92022',
        'price' => '75.00',
        'service' => 2,
    ],
    50 => [
        'county' => 'San Diego',
        'city' => 'La Jolla',
        'zip' => '92023',
        'price' => '75.00',
        'service' => 2,
    ],
    51 => [
        'county' => 'San Diego',
        'city' => 'La Jolla',
        'zip' => '92024',
        'price' => '75.00',
        'service' => 2,
    ],
    52 => [
        'county' => 'San Diego',
        'city' => 'La Jolla',
        'zip' => '92025',
        'price' => '75.00',
        'service' => 2,
    ],
    53 => [
        'county' => 'San Diego',
        'city' => 'La Jolla',
        'zip' => '92026',
        'price' => '75.00',
        'service' => 2,
    ],
    54 => [
        'county' => 'San Diego',
        'city' => 'La Mesa',
        'zip' => '92027',
        'price' => '75.00',
        'service' => 2,
    ],
    55 => [
        'county' => 'San Diego',
        'city' => 'La Mesa',
        'zip' => '92028',
        'price' => '75.00',
        'service' => 2,
    ],
    56 => [
        'county' => 'San Diego',
        'city' => 'La Mesa',
        'zip' => '92029',
        'price' => '75.00',
        'service' => 2,
    ],
    57 => [
        'county' => 'San Diego',
        'city' => 'La Mesa',
        'zip' => '92030',
        'price' => '75.00',
        'service' => 2,
    ],
    58 => [
        'county' => 'San Diego',
        'city' => 'Lakeside',
        'zip' => '92033',
        'price' => '75.00',
        'service' => 2,
    ],
    59 => [
        'county' => 'San Diego',
        'city' => 'Lemon Grove',
        'zip' => '92036',
        'price' => '75.00',
        'service' => 2,
    ],
    60 => [
        'county' => 'San Diego',
        'city' => 'Lemon Grove',
        'zip' => '92037',
        'price' => '75.00',
        'service' => 2,
    ],
    61 => [
        'county' => 'San Diego',
        'city' => 'Lincoln Acres',
        'zip' => '92038',
        'price' => '75.00',
        'service' => 2,
    ],
    62 => [
        'county' => 'San Diego',
        'city' => 'Mount Laguna',
        'zip' => '92039',
        'price' => '75.00',
        'service' => 2,
    ],
    63 => [
        'county' => 'San Diego',
        'city' => 'National City',
        'zip' => '92040',
        'price' => '75.00',
        'service' => 2,
    ],
    64 => [
        'county' => 'San Diego',
        'city' => 'National City',
        'zip' => '92046',
        'price' => '75.00',
        'service' => 2,
    ],
    65 => [
        'county' => 'San Diego',
        'city' => 'Nestor',
        'zip' => '92049',
        'price' => '75.00',
        'service' => 2,
    ],
    66 => [
        'county' => 'San Diego',
        'city' => 'Oceanside',
        'zip' => '92051',
        'price' => '75.00',
        'service' => 2,
    ],
    67 => [
        'county' => 'San Diego',
        'city' => 'Oceanside',
        'zip' => '92052',
        'price' => '75.00',
        'service' => 2,
    ],
    68 => [
        'county' => 'San Diego',
        'city' => 'Oceanside',
        'zip' => '92054',
        'price' => '75.00',
        'service' => 2,
    ],
    69 => [
        'county' => 'San Diego',
        'city' => 'Oceanside',
        'zip' => '92054',
        'price' => '75.00',
        'service' => 2,
    ],
    70 => [
        'county' => 'San Diego',
        'city' => 'Oceanside',
        'zip' => '92055',
        'price' => '75.00',
        'service' => 2,
    ],
    71 => [
        'county' => 'San Diego',
        'city' => 'Oceanside',
        'zip' => '92055',
        'price' => '75.00',
        'service' => 2,
    ],
    72 => [
        'county' => 'San Diego',
        'city' => 'Oceanside',
        'zip' => '92056',
        'price' => '75.00',
        'service' => 2,
    ],
    73 => [
        'county' => 'San Diego',
        'city' => 'Oceanside',
        'zip' => '92057',
        'price' => '75.00',
        'service' => 2,
    ],
    74 => [
        'county' => 'San Diego',
        'city' => 'Pala',
        'zip' => '92058',
        'price' => '95.00',
        'service' => 2,
    ],
    75 => [
        'county' => 'San Diego',
        'city' => 'Pala',
        'zip' => '92059',
        'price' => '95.00',
        'service' => 2,
    ],
    76 => [
        'county' => 'San Diego',
        'city' => 'Palomar Mountain',
        'zip' => '92060',
        'price' => '300.00',
        'service' => 2,
    ],
    77 => [
        'county' => 'San Diego',
        'city' => 'Pauma Valley',
        'zip' => '92061',
        'price' => '95.00',
        'service' => 2,
    ],
    78 => [
        'county' => 'San Diego',
        'city' => 'Pine Valley',
        'zip' => '92061',
        'price' => '95.00',
        'service' => 2,
    ],
    79 => [
        'county' => 'San Diego',
        'city' => 'Potrero',
        'zip' => '92064',
        'price' => '75.00',
        'service' => 2,
    ],
    80 => [
        'county' => 'San Diego',
        'city' => 'Poway',
        'zip' => '92065',
        'price' => '75.00',
        'service' => 2,
    ],
    81 => [
        'county' => 'San Diego',
        'city' => 'Poway',
        'zip' => '92066',
        'price' => '75.00',
        'service' => 2,
    ],
    82 => [
        'county' => 'San Diego',
        'city' => 'Ramona',
        'zip' => '92066',
        'price' => '125.00',
        'service' => 2,
    ],
    83 => [
        'county' => 'San Diego',
        'city' => 'Ranchita',
        'zip' => '92067',
        'price' => '95.00',
        'service' => 2,
    ],
    84 => [
        'county' => 'San Diego',
        'city' => 'Rancho Santa Fe',
        'zip' => '92068',
        'price' => '75.00',
        'service' => 2,
    ],
    85 => [
        'county' => 'San Diego',
        'city' => 'Rancho Santa Fe',
        'zip' => '92069',
        'price' => '75.00',
        'service' => 2,
    ],
    86 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92070',
        'price' => '95.00',
        'service' => 2,
    ],
    87 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92071',
        'price' => '75.00',
        'service' => 2,
    ],
    88 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92072',
        'price' => '75.00',
        'service' => 2,
    ],
    89 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92074',
        'price' => '75.00',
        'service' => 2,
    ],
    90 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92075',
        'price' => '75.00',
        'service' => 2,
    ],
    91 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92078',
        'price' => '75.00',
        'service' => 2,
    ],
    92 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92079',
        'price' => '75.00',
        'service' => 2,
    ],
    93 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92082',
        'price' => '75.00',
        'service' => 2,
    ],
    94 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92083',
        'price' => '75.00',
        'service' => 2,
    ],
    95 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92084',
        'price' => '75.00',
        'service' => 2,
    ],
    96 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92085',
        'price' => '75.00',
        'service' => 2,
    ],
    97 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92086',
        'price' => '75.00',
        'service' => 2,
    ],
    98 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92088',
        'price' => '75.00',
        'service' => 2,
    ],
    99 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92091',
        'price' => '75.00',
        'service' => 2,
    ],
    100 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92092',
        'price' => '75.00',
        'service' => 2,
    ],
    101 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92093',
        'price' => '75.00',
        'service' => 2,
    ],
    102 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92101',
        'price' => '75.00',
        'service' => 2,
    ],
    103 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92102',
        'price' => '75.00',
        'service' => 2,
    ],
    104 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92103',
        'price' => '75.00',
        'service' => 2,
    ],
    105 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92104',
        'price' => '75.00',
        'service' => 2,
    ],
    106 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92105',
        'price' => '75.00',
        'service' => 2,
    ],
    107 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92106',
        'price' => '75.00',
        'service' => 2,
    ],
    108 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92107',
        'price' => '75.00',
        'service' => 2,
    ],
    109 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92108',
        'price' => '75.00',
        'service' => 2,
    ],
    110 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92109',
        'price' => '75.00',
        'service' => 2,
    ],
    111 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92110',
        'price' => '75.00',
        'service' => 2,
    ],
    112 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92111',
        'price' => '75.00',
        'service' => 2,
    ],
    113 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92112',
        'price' => '75.00',
        'service' => 2,
    ],
    114 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92113',
        'price' => '75.00',
        'service' => 2,
    ],
    115 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92114',
        'price' => '75.00',
        'service' => 2,
    ],
    116 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92115',
        'price' => '75.00',
        'service' => 2,
    ],
    117 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92116',
        'price' => '75.00',
        'service' => 2,
    ],
    118 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92117',
        'price' => '75.00',
        'service' => 2,
    ],
    119 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92118',
        'price' => '75.00',
        'service' => 2,
    ],
    120 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92118',
        'price' => '75.00',
        'service' => 2,
    ],
    121 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92119',
        'price' => '75.00',
        'service' => 2,
    ],
    122 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92120',
        'price' => '75.00',
        'service' => 2,
    ],
    123 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92121',
        'price' => '75.00',
        'service' => 2,
    ],
    124 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92122',
        'price' => '75.00',
        'service' => 2,
    ],
    125 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92123',
        'price' => '75.00',
        'service' => 2,
    ],
    126 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92124',
        'price' => '75.00',
        'service' => 2,
    ],
    127 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92126',
        'price' => '75.00',
        'service' => 2,
    ],
    128 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92127',
        'price' => '75.00',
        'service' => 2,
    ],
    129 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92128',
        'price' => '75.00',
        'service' => 2,
    ],
    130 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92129',
        'price' => '75.00',
        'service' => 2,
    ],
    131 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92130',
        'price' => '75.00',
        'service' => 2,
    ],
    132 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92131',
        'price' => '75.00',
        'service' => 2,
    ],
    133 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92132',
        'price' => '75.00',
        'service' => 2,
    ],
    134 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92133',
        'price' => '75.00',
        'service' => 2,
    ],
    135 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92134',
        'price' => '75.00',
        'service' => 2,
    ],
    136 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92135',
        'price' => '75.00',
        'service' => 2,
    ],
    137 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92136',
        'price' => '75.00',
        'service' => 2,
    ],
    138 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92137',
        'price' => '75.00',
        'service' => 2,
    ],
    139 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92138',
        'price' => '75.00',
        'service' => 2,
    ],
    140 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92139',
        'price' => '75.00',
        'service' => 2,
    ],
    141 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92140',
        'price' => '75.00',
        'service' => 2,
    ],
    142 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92142',
        'price' => '75.00',
        'service' => 2,
    ],
    143 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92143',
        'price' => '75.00',
        'service' => 2,
    ],
    144 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92143',
        'price' => '75.00',
        'service' => 2,
    ],
    145 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92145',
        'price' => '75.00',
        'service' => 2,
    ],
    146 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92147',
        'price' => '75.00',
        'service' => 2,
    ],
    147 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92149',
        'price' => '75.00',
        'service' => 2,
    ],
    148 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92150',
        'price' => '75.00',
        'service' => 2,
    ],
    149 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92152',
        'price' => '75.00',
        'service' => 2,
    ],
    150 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92153',
        'price' => '75.00',
        'service' => 2,
    ],
    151 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92153',
        'price' => '75.00',
        'service' => 2,
    ],
    152 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92154',
        'price' => '75.00',
        'service' => 2,
    ],
    153 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92155',
        'price' => '75.00',
        'service' => 2,
    ],
    154 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92159',
        'price' => '75.00',
        'service' => 2,
    ],
    155 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92160',
        'price' => '75.00',
        'service' => 2,
    ],
    156 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92162',
        'price' => '75.00',
        'service' => 2,
    ],
    157 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92163',
        'price' => '75.00',
        'service' => 2,
    ],
    158 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92164',
        'price' => '75.00',
        'service' => 2,
    ],
    159 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92165',
        'price' => '75.00',
        'service' => 2,
    ],
    160 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92166',
        'price' => '75.00',
        'service' => 2,
    ],
    161 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92167',
        'price' => '75.00',
        'service' => 2,
    ],
    162 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92168',
        'price' => '75.00',
        'service' => 2,
    ],
    163 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92169',
        'price' => '75.00',
        'service' => 2,
    ],
    164 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92170',
        'price' => '75.00',
        'service' => 2,
    ],
    165 => [
        'county' => 'San Diego',
        'city' => 'San Diego',
        'zip' => '92171',
        'price' => '75.00',
        'service' => 2,
    ],
    166 => [
        'county' => 'San Diego',
        'city' => 'San Luis Rey',
        'zip' => '92172',
        'price' => '75.00',
        'service' => 2,
    ],
    167 => [
        'county' => 'San Diego',
        'city' => 'San Marcos',
        'zip' => '92173',
        'price' => '75.00',
        'service' => 2,
    ],
    168 => [
        'county' => 'San Diego',
        'city' => 'San Marcos',
        'zip' => '92173',
        'price' => '75.00',
        'service' => 2,
    ],
    169 => [
        'county' => 'San Diego',
        'city' => 'San Marcos',
        'zip' => '92174',
        'price' => '75.00',
        'service' => 2,
    ],
    170 => [
        'county' => 'San Diego',
        'city' => 'San Ysidro',
        'zip' => '92175',
        'price' => '75.00',
        'service' => 2,
    ],
    171 => [
        'county' => 'San Diego',
        'city' => 'San Ysidro',
        'zip' => '92176',
        'price' => '75.00',
        'service' => 2,
    ],
    172 => [
        'county' => 'San Diego',
        'city' => 'Santa Ysabel',
        'zip' => '92177',
        'price' => '75.00',
        'service' => 2,
    ],
    173 => [
        'county' => 'San Diego',
        'city' => 'Santee',
        'zip' => '92178',
        'price' => '75.00',
        'service' => 2,
    ],
    174 => [
        'county' => 'San Diego',
        'city' => 'Santee',
        'zip' => '92178',
        'price' => '125.00',
        'service' => 2,
    ],
    175 => [
        'county' => 'San Diego',
        'city' => 'Solana Beach',
        'zip' => '92182',
        'price' => '75.00',
        'service' => 2,
    ],
    176 => [
        'county' => 'San Diego',
        'city' => 'Spring Valley',
        'zip' => '92186',
        'price' => '75.00',
        'service' => 2,
    ],
    177 => [
        'county' => 'San Diego',
        'city' => 'Spring Valley',
        'zip' => '92190',
        'price' => '75.00',
        'service' => 2,
    ],
    178 => [
        'county' => 'San Diego',
        'city' => 'Spring Valley',
        'zip' => '92191',
        'price' => '75.00',
        'service' => 2,
    ],
    179 => [
        'county' => 'San Diego',
        'city' => 'Spring Valley',
        'zip' => '92192',
        'price' => '75.00',
        'service' => 2,
    ],
    180 => [
        'county' => 'San Diego',
        'city' => 'Tecate',
        'zip' => '92193',
        'price' => '300.00',
        'service' => 2,
    ],
    181 => [
        'county' => 'San Diego',
        'city' => 'Valley Center',
        'zip' => '92194',
        'price' => '75.00',
        'service' => 2,
    ],
    182 => [
        'county' => 'San Diego',
        'city' => 'Vista',
        'zip' => '92195',
        'price' => '75.00',
        'service' => 2,
    ],
    183 => [
        'county' => 'San Diego',
        'city' => 'Vista',
        'zip' => '92196',
        'price' => '75.00',
        'service' => 2,
    ],
    184 => [
        'county' => 'San Diego',
        'city' => 'Vista',
        'zip' => '92197',
        'price' => '75.00',
        'service' => 2,
    ],
    185 => [
        'county' => 'San Diego',
        'city' => 'Warner Springs',
        'zip' => '92198',
        'price' => '300.00',
        'service' => 2,
    ],
    186 => [
        'county' => 'San Diego',
        'city' => 'Warner Springs',
        'zip' => '92199',
        'price' => '300.00',
        'service' => 2,
    ],
    187 => [
        'county' => 'Orange',
        'city' => 'Aliso Viejo',
        'zip' => '92801',
        'price' => '300.00',
        'service' => 2,
    ],
    188 => [
        'county' => 'Orange',
        'city' => 'Aliso Viejo',
        'zip' => '92804',
        'price' => '300.00',
        'service' => 2,
    ],
    189 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92812',
        'price' => '300.00',
        'service' => 2,
    ],
    190 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92814',
        'price' => '300.00',
        'service' => 2,
    ],
    191 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92815',
        'price' => '300.00',
        'service' => 2,
    ],
    192 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92816',
        'price' => '300.00',
        'service' => 2,
    ],
    193 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92817',
        'price' => '300.00',
        'service' => 2,
    ],
    194 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92825',
        'price' => '300.00',
        'service' => 2,
    ],
    195 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92850',
        'price' => '300.00',
        'service' => 2,
    ],
    196 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92823',
        'price' => '300.00',
        'service' => 2,
    ],
    197 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '90620',
        'price' => '300.00',
        'service' => 2,
    ],
    198 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92899',
        'price' => '300.00',
        'service' => 2,
    ],
    199 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92831',
        'price' => '300.00',
        'service' => 2,
    ],
    200 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92832',
        'price' => '300.00',
        'service' => 2,
    ],
    201 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92833',
        'price' => '300.00',
        'service' => 2,
    ],
    202 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92834',
        'price' => '300.00',
        'service' => 2,
    ],
    203 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92835',
        'price' => '300.00',
        'service' => 2,
    ],
    204 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92843',
        'price' => '300.00',
        'service' => 2,
    ],
    205 => [
        'county' => 'Orange',
        'city' => 'Anaheim',
        'zip' => '92844',
        'price' => '300.00',
        'service' => 2,
    ],
    206 => [
        'county' => 'Orange',
        'city' => 'Atwood',
        'zip' => '92845',
        'price' => '300.00',
        'service' => 2,
    ],
    207 => [
        'county' => 'Orange',
        'city' => 'Brea',
        'zip' => '92846',
        'price' => '300.00',
        'service' => 2,
    ],
    208 => [
        'county' => 'Orange',
        'city' => 'Brea',
        'zip' => '92615',
        'price' => '300.00',
        'service' => 2,
    ],
    209 => [
        'county' => 'Orange',
        'city' => 'Brea',
        'zip' => '92646',
        'price' => '300.00',
        'service' => 2,
    ],
    210 => [
        'county' => 'Orange',
        'city' => 'Buena Park',
        'zip' => '92647',
        'price' => '300.00',
        'service' => 2,
    ],
    211 => [
        'county' => 'Orange',
        'city' => 'Buena Park',
        'zip' => '92648',
        'price' => '300.00',
        'service' => 2,
    ],
    212 => [
        'county' => 'Orange',
        'city' => 'Buena Park',
        'zip' => '92649',
        'price' => '300.00',
        'service' => 2,
    ],
    213 => [
        'county' => 'Orange',
        'city' => 'Buena Park',
        'zip' => '92602',
        'price' => '300.00',
        'service' => 2,
    ],
    214 => [
        'county' => 'Orange',
        'city' => 'Capistrano Beach',
        'zip' => '90631',
        'price' => '300.00',
        'service' => 2,
    ],
    215 => [
        'county' => 'Orange',
        'city' => 'Corona Del Mar',
        'zip' => '90632',
        'price' => '300.00',
        'service' => 2,
    ],
    216 => [
        'county' => 'Orange',
        'city' => 'Costa Mesa',
        'zip' => '92656',
        'price' => '300.00',
        'service' => 2,
    ],
    217 => [
        'county' => 'Orange',
        'city' => 'Costa Mesa',
        'zip' => '92698',
        'price' => '300.00',
        'service' => 2,
    ],
    218 => [
        'county' => 'Orange',
        'city' => 'Costa Mesa',
        'zip' => '92805',
        'price' => '300.00',
        'service' => 2,
    ],
    219 => [
        'county' => 'Orange',
        'city' => 'Cypress',
        'zip' => '92806',
        'price' => '300.00',
        'service' => 2,
    ],
    220 => [
        'county' => 'Orange',
        'city' => 'Dana Point',
        'zip' => '92807',
        'price' => '300.00',
        'service' => 2,
    ],
    221 => [
        'county' => 'Orange',
        'city' => 'East Irvine',
        'zip' => '92808',
        'price' => '300.00',
        'service' => 2,
    ],
    222 => [
        'county' => 'Orange',
        'city' => 'El Toro',
        'zip' => '92822',
        'price' => '300.00',
        'service' => 2,
    ],
    223 => [
        'county' => 'Orange',
        'city' => 'Foothill Ranch',
        'zip' => '92809',
        'price' => '300.00',
        'service' => 2,
    ],
    224 => [
        'county' => 'Orange',
        'city' => 'Fountain Valley',
        'zip' => '90621',
        'price' => '300.00',
        'service' => 2,
    ],
    225 => [
        'county' => 'Orange',
        'city' => 'Fountain Valley',
        'zip' => '90622',
        'price' => '300.00',
        'service' => 2,
    ],
    226 => [
        'county' => 'Orange',
        'city' => 'Fullerton',
        'zip' => '90624',
        'price' => '300.00',
        'service' => 2,
    ],
    227 => [
        'county' => 'Orange',
        'city' => 'Fullerton',
        'zip' => '92624',
        'price' => '300.00',
        'service' => 2,
    ],
    228 => [
        'county' => 'Orange',
        'city' => 'Fullerton',
        'zip' => '92625',
        'price' => '300.00',
        'service' => 2,
    ],
    229 => [
        'county' => 'Orange',
        'city' => 'Fullerton',
        'zip' => '92626',
        'price' => '300.00',
        'service' => 2,
    ],
    230 => [
        'county' => 'Orange',
        'city' => 'Fullerton',
        'zip' => '92627',
        'price' => '300.00',
        'service' => 2,
    ],
    231 => [
        'county' => 'Orange',
        'city' => 'Fullerton',
        'zip' => '92628',
        'price' => '300.00',
        'service' => 2,
    ],
    232 => [
        'county' => 'Orange',
        'city' => 'Fullerton',
        'zip' => '90630',
        'price' => '300.00',
        'service' => 2,
    ],
    233 => [
        'county' => 'Orange',
        'city' => 'Fullerton',
        'zip' => '92708',
        'price' => '300.00',
        'service' => 2,
    ],
    234 => [
        'county' => 'Orange',
        'city' => 'Garden Grove',
        'zip' => '92629',
        'price' => '300.00',
        'service' => 2,
    ],
    235 => [
        'county' => 'Orange',
        'city' => 'Garden Grove',
        'zip' => '92650',
        'price' => '300.00',
        'service' => 2,
    ],
    236 => [
        'county' => 'Orange',
        'city' => 'Garden Grove',
        'zip' => '92609',
        'price' => '300.00',
        'service' => 2,
    ],
    237 => [
        'county' => 'Orange',
        'city' => 'Garden Grove',
        'zip' => '92836',
        'price' => '300.00',
        'service' => 2,
    ],
    238 => [
        'county' => 'Orange',
        'city' => 'Garden Grove',
        'zip' => '92837',
        'price' => '300.00',
        'service' => 2,
    ],
    239 => [
        'county' => 'Orange',
        'city' => 'Garden Grove',
        'zip' => '92838',
        'price' => '300.00',
        'service' => 2,
    ],
    240 => [
        'county' => 'Orange',
        'city' => 'Garden Grove',
        'zip' => '92840',
        'price' => '300.00',
        'service' => 2,
    ],
    241 => [
        'county' => 'Orange',
        'city' => 'Huntington Beach',
        'zip' => '92605',
        'price' => '300.00',
        'service' => 2,
    ],
    242 => [
        'county' => 'Orange',
        'city' => 'Huntington Beach',
        'zip' => '92610',
        'price' => '300.00',
        'service' => 2,
    ],
    243 => [
        'county' => 'Orange',
        'city' => 'Huntington Beach',
        'zip' => '92604',
        'price' => '300.00',
        'service' => 2,
    ],
    244 => [
        'county' => 'Orange',
        'city' => 'Huntington Beach',
        'zip' => '92606',
        'price' => '300.00',
        'service' => 2,
    ],
    245 => [
        'county' => 'Orange',
        'city' => 'Huntington Beach',
        'zip' => '92612',
        'price' => '300.00',
        'service' => 2,
    ],
    246 => [
        'county' => 'Orange',
        'city' => 'Huntington Beach',
        'zip' => '92802',
        'price' => '300.00',
        'service' => 2,
    ],
    247 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92614',
        'price' => '300.00',
        'service' => 2,
    ],
    248 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92616',
        'price' => '300.00',
        'service' => 2,
    ],
    249 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92803',
        'price' => '300.00',
        'service' => 2,
    ],
    250 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92618',
        'price' => '300.00',
        'service' => 2,
    ],
    251 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92619',
        'price' => '300.00',
        'service' => 2,
    ],
    252 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92620',
        'price' => '300.00',
        'service' => 2,
    ],
    253 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92623',
        'price' => '300.00',
        'service' => 2,
    ],
    254 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92709',
        'price' => '300.00',
        'service' => 2,
    ],
    255 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92697',
        'price' => '300.00',
        'service' => 2,
    ],
    256 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92710',
        'price' => '300.00',
        'service' => 2,
    ],
    257 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '90633',
        'price' => '300.00',
        'service' => 2,
    ],
    258 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92694',
        'price' => '300.00',
        'service' => 2,
    ],
    259 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92651',
        'price' => '300.00',
        'service' => 2,
    ],
    260 => [
        'county' => 'Orange',
        'city' => 'Irvine',
        'zip' => '92652',
        'price' => '300.00',
        'service' => 2,
    ],
    261 => [
        'county' => 'Orange',
        'city' => 'La Habra',
        'zip' => '90623',
        'price' => '300.00',
        'service' => 2,
    ],
    262 => [
        'county' => 'Orange',
        'city' => 'La Habra',
        'zip' => '92728',
        'price' => '300.00',
        'service' => 2,
    ],
    263 => [
        'county' => 'Orange',
        'city' => 'La Habra',
        'zip' => '92637',
        'price' => '300.00',
        'service' => 2,
    ],
    264 => [
        'county' => 'Orange',
        'city' => 'La Palma',
        'zip' => '92841',
        'price' => '300.00',
        'service' => 2,
    ],
    265 => [
        'county' => 'Orange',
        'city' => 'Ladera Ranch',
        'zip' => '92842',
        'price' => '300.00',
        'service' => 2,
    ],
    266 => [
        'county' => 'Orange',
        'city' => 'Laguna Beach',
        'zip' => '92653',
        'price' => '300.00',
        'service' => 2,
    ],
    267 => [
        'county' => 'Orange',
        'city' => 'Laguna Beach',
        'zip' => '92654',
        'price' => '300.00',
        'service' => 2,
    ],
    268 => [
        'county' => 'Orange',
        'city' => 'Laguna Hills',
        'zip' => '92607',
        'price' => '300.00',
        'service' => 2,
    ],
    269 => [
        'county' => 'Orange',
        'city' => 'Laguna Hills',
        'zip' => '92677',
        'price' => '300.00',
        'service' => 2,
    ],
    270 => [
        'county' => 'Orange',
        'city' => 'Laguna Hills',
        'zip' => '92630',
        'price' => '300.00',
        'service' => 2,
    ],
    271 => [
        'county' => 'Orange',
        'city' => 'Laguna Niguel',
        'zip' => '90720',
        'price' => '300.00',
        'service' => 2,
    ],
    272 => [
        'county' => 'Orange',
        'city' => 'Laguna Niguel',
        'zip' => '90721',
        'price' => '300.00',
        'service' => 2,
    ],
    273 => [
        'county' => 'Orange',
        'city' => 'Lake Forest',
        'zip' => '92655',
        'price' => '300.00',
        'service' => 2,
    ],
    274 => [
        'county' => 'Orange',
        'city' => 'Los Alamitos',
        'zip' => '92690',
        'price' => '300.00',
        'service' => 2,
    ],
    275 => [
        'county' => 'Orange',
        'city' => 'Los Alamitos',
        'zip' => '92691',
        'price' => '300.00',
        'service' => 2,
    ],
    276 => [
        'county' => 'Orange',
        'city' => 'Midway City',
        'zip' => '92692',
        'price' => '300.00',
        'service' => 2,
    ],
    277 => [
        'county' => 'Orange',
        'city' => 'Mission Viejo',
        'zip' => '92658',
        'price' => '300.00',
        'service' => 2,
    ],
    278 => [
        'county' => 'Orange',
        'city' => 'Mission Viejo',
        'zip' => '92659',
        'price' => '300.00',
        'service' => 2,
    ],
    279 => [
        'county' => 'Orange',
        'city' => 'Mission Viejo',
        'zip' => '92660',
        'price' => '300.00',
        'service' => 2,
    ],
    280 => [
        'county' => 'Orange',
        'city' => 'Newport Beach',
        'zip' => '92661',
        'price' => '300.00',
        'service' => 2,
    ],
    281 => [
        'county' => 'Orange',
        'city' => 'Newport Beach',
        'zip' => '92662',
        'price' => '300.00',
        'service' => 2,
    ],
    282 => [
        'county' => 'Orange',
        'city' => 'Newport Beach',
        'zip' => '92663',
        'price' => '300.00',
        'service' => 2,
    ],
    283 => [
        'county' => 'Orange',
        'city' => 'Newport Beach',
        'zip' => '92811',
        'price' => '300.00',
        'service' => 2,
    ],
    284 => [
        'county' => 'Orange',
        'city' => 'Newport Beach',
        'zip' => '92657',
        'price' => '300.00',
        'service' => 2,
    ],
    285 => [
        'county' => 'Orange',
        'city' => 'Newport Beach',
        'zip' => '92856',
        'price' => '300.00',
        'service' => 2,
    ],
    286 => [
        'county' => 'Orange',
        'city' => 'Newport Coast',
        'zip' => '92857',
        'price' => '300.00',
        'service' => 2,
    ],
    287 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92859',
        'price' => '300.00',
        'service' => 2,
    ],
    288 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92862',
        'price' => '300.00',
        'service' => 2,
    ],
    289 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92863',
        'price' => '300.00',
        'service' => 2,
    ],
    290 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92864',
        'price' => '300.00',
        'service' => 2,
    ],
    291 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92865',
        'price' => '300.00',
        'service' => 2,
    ],
    292 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92866',
        'price' => '300.00',
        'service' => 2,
    ],
    293 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92867',
        'price' => '300.00',
        'service' => 2,
    ],
    294 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92868',
        'price' => '300.00',
        'service' => 2,
    ],
    295 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92869',
        'price' => '300.00',
        'service' => 2,
    ],
    296 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92870',
        'price' => '300.00',
        'service' => 2,
    ],
    297 => [
        'county' => 'Orange',
        'city' => 'Orange',
        'zip' => '92871',
        'price' => '300.00',
        'service' => 2,
    ],
    298 => [
        'county' => 'Orange',
        'city' => 'Placentia',
        'zip' => '92688',
        'price' => '300.00',
        'service' => 2,
    ],
    299 => [
        'county' => 'Orange',
        'city' => 'Placentia',
        'zip' => '92672',
        'price' => '300.00',
        'service' => 2,
    ],
    300 => [
        'county' => 'Orange',
        'city' => 'Rancho Santa Margarita',
        'zip' => '92673',
        'price' => '300.00',
        'service' => 2,
    ],
    301 => [
        'county' => 'Orange',
        'city' => 'San Clemente',
        'zip' => '92674',
        'price' => '300.00',
        'service' => 2,
    ],
    302 => [
        'county' => 'Orange',
        'city' => 'San Clemente',
        'zip' => '92675',
        'price' => '300.00',
        'service' => 2,
    ],
    303 => [
        'county' => 'Orange',
        'city' => 'San Clemente',
        'zip' => '92693',
        'price' => '300.00',
        'service' => 2,
    ],
    304 => [
        'county' => 'Orange',
        'city' => 'San Juan Capistrano',
        'zip' => '92701',
        'price' => '300.00',
        'service' => 2,
    ],
    305 => [
        'county' => 'Orange',
        'city' => 'San Juan Capistrano',
        'zip' => '92702',
        'price' => '300.00',
        'service' => 2,
    ],
    306 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92703',
        'price' => '300.00',
        'service' => 2,
    ],
    307 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92704',
        'price' => '300.00',
        'service' => 2,
    ],
    308 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92705',
        'price' => '300.00',
        'service' => 2,
    ],
    309 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92706',
        'price' => '300.00',
        'service' => 2,
    ],
    310 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92707',
        'price' => '300.00',
        'service' => 2,
    ],
    311 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92711',
        'price' => '300.00',
        'service' => 2,
    ],
    312 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92712',
        'price' => '300.00',
        'service' => 2,
    ],
    313 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92603',
        'price' => '300.00',
        'service' => 2,
    ],
    314 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92725',
        'price' => '300.00',
        'service' => 2,
    ],
    315 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92735',
        'price' => '300.00',
        'service' => 2,
    ],
    316 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '92799',
        'price' => '300.00',
        'service' => 2,
    ],
    317 => [
        'county' => 'Orange',
        'city' => 'Santa Ana',
        'zip' => '90740',
        'price' => '300.00',
        'service' => 2,
    ],
    318 => [
        'county' => 'Orange',
        'city' => 'Seal Beach',
        'zip' => '92676',
        'price' => '300.00',
        'service' => 2,
    ],
    319 => [
        'county' => 'Orange',
        'city' => 'Silverado',
        'zip' => '90680',
        'price' => '300.00',
        'service' => 2,
    ],
    320 => [
        'county' => 'Orange',
        'city' => 'Stanton',
        'zip' => '90742',
        'price' => '300.00',
        'service' => 2,
    ],
    321 => [
        'county' => 'Orange',
        'city' => 'Sunset Beach',
        'zip' => '90743',
        'price' => '300.00',
        'service' => 2,
    ],
    322 => [
        'county' => 'Orange',
        'city' => 'Surfside',
        'zip' => '92678',
        'price' => '300.00',
        'service' => 2,
    ],
    323 => [
        'county' => 'Orange',
        'city' => 'Trabuco Canyon',
        'zip' => '92679',
        'price' => '300.00',
        'service' => 2,
    ],
    324 => [
        'county' => 'Orange',
        'city' => 'Trabuco Canyon',
        'zip' => '92780',
        'price' => '300.00',
        'service' => 2,
    ],
    325 => [
        'county' => 'Orange',
        'city' => 'Tustin',
        'zip' => '92781',
        'price' => '300.00',
        'service' => 2,
    ],
    326 => [
        'county' => 'Orange',
        'city' => 'Tustin',
        'zip' => '92782',
        'price' => '300.00',
        'service' => 2,
    ],
    327 => [
        'county' => 'Orange',
        'city' => 'Tustin',
        'zip' => '92861',
        'price' => '300.00',
        'service' => 2,
    ],
    328 => [
        'county' => 'Orange',
        'city' => 'Villa Park',
        'zip' => '92683',
        'price' => '300.00',
        'service' => 2,
    ],
    329 => [
        'county' => 'Orange',
        'city' => 'Westminster',
        'zip' => '92684',
        'price' => '300.00',
        'service' => 2,
    ],
    330 => [
        'county' => 'Orange',
        'city' => 'Westminster',
        'zip' => '92685',
        'price' => '300.00',
        'service' => 2,
    ],
    331 => [
        'county' => 'Orange',
        'city' => 'Westminster',
        'zip' => '92885',
        'price' => '300.00',
        'service' => 2,
    ],
    332 => [
        'county' => 'Orange',
        'city' => 'Yorba Linda',
        'zip' => '92886',
        'price' => '300.00',
        'service' => 2,
    ],
    333 => [
        'county' => 'Orange',
        'city' => 'Yorba Linda',
        'zip' => '92887',
        'price' => '300.00',
        'service' => 2,
    ],
    334 => [
        'county' => 'Orange',
        'city' => 'Yorba Linda',
        'zip' => '92821',
        'price' => '300.00',
        'service' => 2,
    ],
    335 => [
        'county' => 'Riverside',
        'city' => 'Aguanga',
        'zip' => '91752',
        'price' => '150.00',
        'service' => 2,
    ],
    336 => [
        'county' => 'Riverside',
        'city' => 'Anza',
        'zip' => '92201',
        'price' => '150.00',
        'service' => 2,
    ],
    337 => [
        'county' => 'Riverside',
        'city' => 'Banning',
        'zip' => '92201',
        'price' => '150.00',
        'service' => 2,
    ],
    338 => [
        'county' => 'Riverside',
        'city' => 'Beaumont',
        'zip' => '92201',
        'price' => '150.00',
        'service' => 2,
    ],
    339 => [
        'county' => 'Riverside',
        'city' => 'Blythe',
        'zip' => '92202',
        'price' => '150.00',
        'service' => 2,
    ],
    340 => [
        'county' => 'Riverside',
        'city' => 'Blythe',
        'zip' => '92203',
        'price' => '150.00',
        'service' => 2,
    ],
    341 => [
        'county' => 'Riverside',
        'city' => 'Cabazon',
        'zip' => '92210',
        'price' => '150.00',
        'service' => 2,
    ],
    342 => [
        'county' => 'Riverside',
        'city' => 'Cabazon',
        'zip' => '92210',
        'price' => '150.00',
        'service' => 2,
    ],
    343 => [
        'county' => 'Riverside',
        'city' => 'Calimesa',
        'zip' => '92211',
        'price' => '150.00',
        'service' => 2,
    ],
    344 => [
        'county' => 'Riverside',
        'city' => 'Canyon Lake',
        'zip' => '92220',
        'price' => '150.00',
        'service' => 2,
    ],
    345 => [
        'county' => 'Riverside',
        'city' => 'Cathedral City',
        'zip' => '92223',
        'price' => '150.00',
        'service' => 2,
    ],
    346 => [
        'county' => 'Riverside',
        'city' => 'Cathedral City',
        'zip' => '92223',
        'price' => '150.00',
        'service' => 2,
    ],
    347 => [
        'county' => 'Riverside',
        'city' => 'Cherry Valley',
        'zip' => '92225',
        'price' => '150.00',
        'service' => 2,
    ],
    348 => [
        'county' => 'Riverside',
        'city' => 'Chiriaco Smt',
        'zip' => '92225',
        'price' => '150.00',
        'service' => 2,
    ],
    349 => [
        'county' => 'Riverside',
        'city' => 'Chiriaco Summit',
        'zip' => '92226',
        'price' => '150.00',
        'service' => 2,
    ],
    350 => [
        'county' => 'Riverside',
        'city' => 'Coachella',
        'zip' => '92230',
        'price' => '150.00',
        'service' => 2,
    ],
    351 => [
        'county' => 'Riverside',
        'city' => 'Corona',
        'zip' => '92234',
        'price' => '150.00',
        'service' => 2,
    ],
    352 => [
        'county' => 'Riverside',
        'city' => 'Corona',
        'zip' => '92235',
        'price' => '150.00',
        'service' => 2,
    ],
    353 => [
        'county' => 'Riverside',
        'city' => 'Corona',
        'zip' => '92236',
        'price' => '150.00',
        'service' => 2,
    ],
    354 => [
        'county' => 'Riverside',
        'city' => 'Corona',
        'zip' => '92239',
        'price' => '150.00',
        'service' => 2,
    ],
    355 => [
        'county' => 'Riverside',
        'city' => 'Corona',
        'zip' => '92239',
        'price' => '150.00',
        'service' => 2,
    ],
    356 => [
        'county' => 'Riverside',
        'city' => 'Corona',
        'zip' => '92240',
        'price' => '150.00',
        'service' => 2,
    ],
    357 => [
        'county' => 'Riverside',
        'city' => 'Corona',
        'zip' => '92241',
        'price' => '150.00',
        'service' => 2,
    ],
    358 => [
        'county' => 'Riverside',
        'city' => 'Desert Center',
        'zip' => '92253',
        'price' => '150.00',
        'service' => 2,
    ],
    359 => [
        'county' => 'Riverside',
        'city' => 'Desert Hot Springs',
        'zip' => '92254',
        'price' => '150.00',
        'service' => 2,
    ],
    360 => [
        'county' => 'Riverside',
        'city' => 'Desert Hot Springs',
        'zip' => '92255',
        'price' => '150.00',
        'service' => 2,
    ],
    361 => [
        'county' => 'Riverside',
        'city' => 'Eagle Mountain',
        'zip' => '92258',
        'price' => '150.00',
        'service' => 2,
    ],
    362 => [
        'county' => 'Riverside',
        'city' => 'Gilman Hot Springs',
        'zip' => '92258',
        'price' => '150.00',
        'service' => 2,
    ],
    363 => [
        'county' => 'Riverside',
        'city' => 'Hemet',
        'zip' => '92260',
        'price' => '150.00',
        'service' => 2,
    ],
    364 => [
        'county' => 'Riverside',
        'city' => 'Hemet',
        'zip' => '92261',
        'price' => '150.00',
        'service' => 2,
    ],
    365 => [
        'county' => 'Riverside',
        'city' => 'Hemet',
        'zip' => '92262',
        'price' => '150.00',
        'service' => 2,
    ],
    366 => [
        'county' => 'Riverside',
        'city' => 'Hemet',
        'zip' => '92263',
        'price' => '150.00',
        'service' => 2,
    ],
    367 => [
        'county' => 'Riverside',
        'city' => 'Homeland',
        'zip' => '92264',
        'price' => '150.00',
        'service' => 2,
    ],
    368 => [
        'county' => 'Riverside',
        'city' => 'Idyllwild',
        'zip' => '92270',
        'price' => '150.00',
        'service' => 2,
    ],
    369 => [
        'county' => 'Riverside',
        'city' => 'Indian Wells',
        'zip' => '92274',
        'price' => '150.00',
        'service' => 2,
    ],
    370 => [
        'county' => 'Riverside',
        'city' => 'Indio',
        'zip' => '92276',
        'price' => '150.00',
        'service' => 2,
    ],
    371 => [
        'county' => 'Riverside',
        'city' => 'Indio',
        'zip' => '92282',
        'price' => '150.00',
        'service' => 2,
    ],
    372 => [
        'county' => 'Riverside',
        'city' => 'Indio',
        'zip' => '92282',
        'price' => '150.00',
        'service' => 2,
    ],
    373 => [
        'county' => 'Riverside',
        'city' => 'La Quinta',
        'zip' => '92292',
        'price' => '150.00',
        'service' => 2,
    ],
    374 => [
        'county' => 'Riverside',
        'city' => 'Lake Elsinore',
        'zip' => '92320',
        'price' => '150.00',
        'service' => 2,
    ],
    375 => [
        'county' => 'Riverside',
        'city' => 'Lake Elsinore',
        'zip' => '92501',
        'price' => '150.00',
        'service' => 2,
    ],
    376 => [
        'county' => 'Riverside',
        'city' => 'Lake Elsinore',
        'zip' => '92502',
        'price' => '150.00',
        'service' => 2,
    ],
    377 => [
        'county' => 'Riverside',
        'city' => 'Lakeview',
        'zip' => '92503',
        'price' => '150.00',
        'service' => 2,
    ],
    378 => [
        'county' => 'Riverside',
        'city' => 'March Air Force Base',
        'zip' => '92504',
        'price' => '150.00',
        'service' => 2,
    ],
    379 => [
        'county' => 'Riverside',
        'city' => 'March Air Reserve Base',
        'zip' => '92505',
        'price' => '150.00',
        'service' => 2,
    ],
    380 => [
        'county' => 'Riverside',
        'city' => 'Mecca',
        'zip' => '92506',
        'price' => '150.00',
        'service' => 2,
    ],
    381 => [
        'county' => 'Riverside',
        'city' => 'Menifee',
        'zip' => '92507',
        'price' => '150.00',
        'service' => 2,
    ],
    382 => [
        'county' => 'Riverside',
        'city' => 'Mira Loma',
        'zip' => '92508',
        'price' => '150.00',
        'service' => 2,
    ],
    383 => [
        'county' => 'Riverside',
        'city' => 'Moreno Valley',
        'zip' => '92509',
        'price' => '150.00',
        'service' => 2,
    ],
    384 => [
        'county' => 'Riverside',
        'city' => 'Moreno Valley',
        'zip' => '92509',
        'price' => '150.00',
        'service' => 2,
    ],
    385 => [
        'county' => 'Riverside',
        'city' => 'Moreno Valley',
        'zip' => '92513',
        'price' => '150.00',
        'service' => 2,
    ],
    386 => [
        'county' => 'Riverside',
        'city' => 'Moreno Valley',
        'zip' => '92514',
        'price' => '150.00',
        'service' => 2,
    ],
    387 => [
        'county' => 'Riverside',
        'city' => 'Moreno Valley',
        'zip' => '92515',
        'price' => '150.00',
        'service' => 2,
    ],
    388 => [
        'county' => 'Riverside',
        'city' => 'Moreno Valley',
        'zip' => '92516',
        'price' => '150.00',
        'service' => 2,
    ],
    389 => [
        'county' => 'Riverside',
        'city' => 'Moreno Valley',
        'zip' => '92517',
        'price' => '150.00',
        'service' => 2,
    ],
    390 => [
        'county' => 'Riverside',
        'city' => 'Mountain Center',
        'zip' => '92518',
        'price' => '150.00',
        'service' => 2,
    ],
    391 => [
        'county' => 'Riverside',
        'city' => 'Murrieta',
        'zip' => '92518',
        'price' => '150.00',
        'service' => 2,
    ],
    392 => [
        'county' => 'Riverside',
        'city' => 'Murrieta',
        'zip' => '92518',
        'price' => '150.00',
        'service' => 2,
    ],
    393 => [
        'county' => 'Riverside',
        'city' => 'Murrieta',
        'zip' => '92519',
        'price' => '150.00',
        'service' => 2,
    ],
    394 => [
        'county' => 'Riverside',
        'city' => 'No Palm Springs',
        'zip' => '92530',
        'price' => '75.00',
        'service' => 2,
    ],
    395 => [
        'county' => 'Riverside',
        'city' => 'Norco',
        'zip' => '92531',
        'price' => '75.00',
        'service' => 2,
    ],
    396 => [
        'county' => 'Riverside',
        'city' => 'North Palm Springs',
        'zip' => '92532',
        'price' => '75.00',
        'service' => 2,
    ],
    397 => [
        'county' => 'Riverside',
        'city' => 'Nuevo',
        'zip' => '92536',
        'price' => '150.00',
        'service' => 2,
    ],
    398 => [
        'county' => 'Riverside',
        'city' => 'Palm Desert',
        'zip' => '92539',
        'price' => '150.00',
        'service' => 2,
    ],
    399 => [
        'county' => 'Riverside',
        'city' => 'Palm Desert',
        'zip' => '92543',
        'price' => '150.00',
        'service' => 2,
    ],
    400 => [
        'county' => 'Riverside',
        'city' => 'Palm Desert',
        'zip' => '92544',
        'price' => '150.00',
        'service' => 2,
    ],
    401 => [
        'county' => 'Riverside',
        'city' => 'Palm Desert',
        'zip' => '92545',
        'price' => '150.00',
        'service' => 2,
    ],
    402 => [
        'county' => 'Riverside',
        'city' => 'Palm Desert',
        'zip' => '92546',
        'price' => '150.00',
        'service' => 2,
    ],
    403 => [
        'county' => 'Riverside',
        'city' => 'Palm Springs',
        'zip' => '92548',
        'price' => '150.00',
        'service' => 2,
    ],
    404 => [
        'county' => 'Riverside',
        'city' => 'Palm Springs',
        'zip' => '92549',
        'price' => '150.00',
        'service' => 2,
    ],
    405 => [
        'county' => 'Riverside',
        'city' => 'Palm Springs',
        'zip' => '92551',
        'price' => '150.00',
        'service' => 2,
    ],
    406 => [
        'county' => 'Riverside',
        'city' => 'Palm Springs',
        'zip' => '92552',
        'price' => '150.00',
        'service' => 2,
    ],
    407 => [
        'county' => 'Riverside',
        'city' => 'Perris',
        'zip' => '92553',
        'price' => '150.00',
        'service' => 2,
    ],
    408 => [
        'county' => 'Riverside',
        'city' => 'Perris',
        'zip' => '92554',
        'price' => '150.00',
        'service' => 2,
    ],
    409 => [
        'county' => 'Riverside',
        'city' => 'Perris',
        'zip' => '92555',
        'price' => '150.00',
        'service' => 2,
    ],
    410 => [
        'county' => 'Riverside',
        'city' => 'Quail Valley',
        'zip' => '92556',
        'price' => '150.00',
        'service' => 2,
    ],
    411 => [
        'county' => 'Riverside',
        'city' => 'Rancho Mirage',
        'zip' => '92557',
        'price' => '150.00',
        'service' => 2,
    ],
    412 => [
        'county' => 'Riverside',
        'city' => 'Ripley',
        'zip' => '92561',
        'price' => '150.00',
        'service' => 2,
    ],
    413 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92562',
        'price' => '75.00',
        'service' => 2,
    ],
    414 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92563',
        'price' => '75.00',
        'service' => 2,
    ],
    415 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92564',
        'price' => '75.00',
        'service' => 2,
    ],
    416 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92567',
        'price' => '75.00',
        'service' => 2,
    ],
    417 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92567',
        'price' => '75.00',
        'service' => 2,
    ],
    418 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92570',
        'price' => '75.00',
        'service' => 2,
    ],
    419 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92571',
        'price' => '75.00',
        'service' => 2,
    ],
    420 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92572',
        'price' => '75.00',
        'service' => 2,
    ],
    421 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92581',
        'price' => '75.00',
        'service' => 2,
    ],
    422 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92582',
        'price' => '75.00',
        'service' => 2,
    ],
    423 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92583',
        'price' => '75.00',
        'service' => 2,
    ],
    424 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92583',
        'price' => '75.00',
        'service' => 2,
    ],
    425 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92584',
        'price' => '75.00',
        'service' => 2,
    ],
    426 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92584',
        'price' => '75.00',
        'service' => 2,
    ],
    427 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92585',
        'price' => '75.00',
        'service' => 2,
    ],
    428 => [
        'county' => 'Riverside',
        'city' => 'Riverside',
        'zip' => '92585',
        'price' => '75.00',
        'service' => 2,
    ],
    429 => [
        'county' => 'Riverside',
        'city' => 'Romoland',
        'zip' => '92586',
        'price' => '75.00',
        'service' => 2,
    ],
    430 => [
        'county' => 'Riverside',
        'city' => 'Rubidoux',
        'zip' => '92587',
        'price' => '75.00',
        'service' => 2,
    ],
    431 => [
        'county' => 'Riverside',
        'city' => 'San Jacinto',
        'zip' => '92587',
        'price' => '75.00',
        'service' => 2,
    ],
    432 => [
        'county' => 'Riverside',
        'city' => 'San Jacinto',
        'zip' => '92587',
        'price' => '75.00',
        'service' => 2,
    ],
    433 => [
        'county' => 'Riverside',
        'city' => 'San Jacinto',
        'zip' => '92589',
        'price' => '75.00',
        'service' => 2,
    ],
    434 => [
        'county' => 'Riverside',
        'city' => 'Sun City',
        'zip' => '92590',
        'price' => '75.00',
        'service' => 2,
    ],
    435 => [
        'county' => 'Riverside',
        'city' => 'Sun City',
        'zip' => '92591',
        'price' => '75.00',
        'service' => 2,
    ],
    436 => [
        'county' => 'Riverside',
        'city' => 'Sun City',
        'zip' => '92592',
        'price' => '75.00',
        'service' => 2,
    ],
    437 => [
        'county' => 'Riverside',
        'city' => 'Sun City',
        'zip' => '92593',
        'price' => '75.00',
        'service' => 2,
    ],
    438 => [
        'county' => 'Riverside',
        'city' => 'Temecula',
        'zip' => '92595',
        'price' => '150.00',
        'service' => 2,
    ],
    439 => [
        'county' => 'Riverside',
        'city' => 'Temecula',
        'zip' => '92596',
        'price' => '150.00',
        'service' => 2,
    ],
    440 => [
        'county' => 'Riverside',
        'city' => 'Temecula',
        'zip' => '92860',
        'price' => '150.00',
        'service' => 2,
    ],
    441 => [
        'county' => 'Riverside',
        'city' => 'Temecula',
        'zip' => '92877',
        'price' => '150.00',
        'service' => 2,
    ],
    442 => [
        'county' => 'Riverside',
        'city' => 'Temecula',
        'zip' => '92878',
        'price' => '150.00',
        'service' => 2,
    ],
    443 => [
        'county' => 'Riverside',
        'city' => 'Thermal',
        'zip' => '92879',
        'price' => '125.00',
        'service' => 2,
    ],
    444 => [
        'county' => 'Riverside',
        'city' => 'Thousand Palms',
        'zip' => '92880',
        'price' => '125.00',
        'service' => 2,
    ],
    445 => [
        'county' => 'Riverside',
        'city' => 'White Water',
        'zip' => '92881',
        'price' => '125.00',
        'service' => 2,
    ],
    446 => [
        'county' => 'Riverside',
        'city' => 'Wildomar',
        'zip' => '92882',
        'price' => '125.00',
        'service' => 2,
    ],
    447 => [
        'county' => 'Riverside',
        'city' => 'Winchester',
        'zip' => '92883',
        'price' => '125.00',
        'service' => 2,
    ],
];
