export const CHOOSE_SERVICE = "CHOOSE_SERVICE";
export const DATE_AND_TIME = "DATE_AND_TIME";
export const ORDER_DESCRIPTION = "ORDER_DESCRIPTION";
export const CONTACT_INFO = "CONTACT_INFO";
export const REVIEW_YOUR_ORDER = "REVIEW_YOUR_ORDER";
